# Generated by Django 3.2.8 on 2021-12-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.IntegerField()),
                ('subname', models.CharField(max_length=200)),
                ('chname', models.CharField(max_length=80)),
                ('quickmap', models.ImageField(upload_to='')),
            ],
        ),
    ]
