# Generated by Django 3.2.8 on 2021-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quickmap', '0002_alter_quickmap_quickmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickmap',
            name='quickmap',
            field=models.ImageField(upload_to='E:\\HTML,CSS,Javascript\\Django\\Django Learning\\Tenthies\\static\\images'),
        ),
    ]
