# Generated by Django 3.2.8 on 2022-01-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
