# Generated by Django 3.2.8 on 2022-01-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20220112_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='dislike',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
    ]
