# Generated by Django 3.2.8 on 2021-12-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.IntegerField()),
                ('subname', models.TextField()),
                ('chname', models.CharField(max_length=400)),
                ('pdf', models.FileField(upload_to='E:\\HTML,CSS,Javascript\\Django\\Django Learning\\Tenthies\\static\\pdfs')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.subject')),
            ],
        ),
    ]
