# Generated by Django 3.2.8 on 2021-12-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.IntegerField()),
                ('subname', models.TextField()),
                ('chname', models.TextField()),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
