# Generated by Django 3.2.8 on 2021-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_alter_resource_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pdf',
            field=models.FileField(upload_to='E:\\HTML,CSS,Javascript\\Django\\Django Learning\\Tenthies\\static\\pdfs'),
        ),
    ]
