# Generated by Django 3.2.8 on 2021-12-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_alter_resource_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pdf',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
