# Generated by Django 3.2.8 on 2022-01-16 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('option1', models.CharField(max_length=400)),
                ('option2', models.CharField(max_length=400)),
                ('option3', models.CharField(max_length=400)),
                ('option4', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(default='', max_length=30)),
                ('subcode', models.IntegerField()),
                ('subname', models.CharField(max_length=200)),
                ('level', models.TextField()),
                ('chname', models.CharField(max_length=200)),
                ('totalquestions', models.IntegerField()),
                ('subimg', models.ImageField(upload_to='images')),
                ('sub_bgcolor', models.CharField(max_length=7)),
                ('sub_bgcolor_light', models.CharField(max_length=10)),
                ('sub_textcolor_hover', models.CharField(max_length=10)),
                ('sub_boxshadow_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksobtained', models.IntegerField()),
                ('totalmarks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('subcode', models.IntegerField()),
                ('subname', models.CharField(max_length=200)),
                ('level', models.TextField()),
                ('chname', models.CharField(max_length=200)),
                ('questions', models.TextField(default='')),
                ('useranswers', models.TextField(default='')),
                ('correctanswer', models.TextField(default='')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.IntegerField(null=True)),
                ('button', models.CharField(max_length=40, null=True)),
                ('useranswer', models.TextField(default='', null=True)),
                ('questions', models.ManyToManyField(null=True, to='Quiz.Question')),
                ('subject', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Quiz.subject')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Quiz.subject'),
        ),
    ]
