# Generated by Django 3.2.8 on 2021-12-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
    ]
