# Generated by Django 3.2.8 on 2021-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20211230_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subimg',
            field=models.ImageField(upload_to='E:\\HTML,CSS,Javascript\\Django\\Django Learning\\Tenthies\\static\\images'),
        ),
    ]
