# Generated by Django 3.2.8 on 2021-12-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_subject_subimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subimg',
            field=models.ImageField(upload_to='images'),
        ),
    ]
