# Generated by Django 3.2.8 on 2022-01-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_subject_subimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chname',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subname',
        ),
    ]
