# Generated by Django 3.2.8 on 2021-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_quizresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='totalquestions',
            field=models.IntegerField(default=10),
        ),
    ]
