# Generated by Django 3.2.8 on 2022-01-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20220103_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='answers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='questions',
            field=models.TextField(default=''),
        ),
    ]
