# Generated by Django 3.2.8 on 2022-01-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_remove_quizdetails_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdetails',
            name='questions',
            field=models.ManyToManyField(to='Quiz.Question'),
        ),
    ]
