# Generated by Django 3.2.8 on 2022-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='best_subject_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weak_subject_marks',
            field=models.IntegerField(default=0),
        ),
    ]
