# Generated by Django 3.2.8 on 2022-01-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20220110_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seenby',
            field=models.TextField(default=''),
        ),
    ]
