# Generated by Django 3.2.8 on 2022-01-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_profile_seenby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='seenby',
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
