# Generated by Django 3.2.8 on 2022-01-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_auto_20220117_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weak_subject_marks',
            field=models.IntegerField(default=1000),
        ),
    ]
