# Generated by Django 3.2.8 on 2021-12-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
