# Generated by Django 3.2.8 on 2021-12-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MUser',
        ),
    ]
