# Generated by Django 3.2.8 on 2022-01-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_alter_quizresult_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('User', '0003_muser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MUser',
        ),
    ]
